name: Docker Image CI

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  build:
    # 1. Change this line from 'ubuntu-latest' to 'self-hosted'
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image Directly on Local Server
      run: |
        docker build -t py-api-mysql:latest .

    - name: Run or Refresh Local Container
      run: |
        docker stop fastapi-app || true
        docker rm fastapi-app || true
        docker run -d \
          --restart unless-stopped \
          --name fastapi-app \
          -p 8000:8000 \
          -e DB_HOST="host.docker.internal" \
          -e DB_USER="root" \
          -e DB_PASSWORD="DB_secure_password" \
          -e DB_NAME="company_db" \
          --add-host=host.docker.internal:host-gateway \
          py-api-mysql:latest
